
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'services/firestore_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:verdoro/l10n/app_localizations.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:google_fonts/google_fonts.dart';
// AppLocalizations is generated by flutter gen-l10n from lib/l10n/app_*.arb

import 'firebase_options.dart';
import 'services/notification_service.dart';
import 'services/theme_service.dart';
import 'services/locale_service.dart';
import 'theme/app_theme.dart';
import 'screens/home_screen.dart';
import 'screens/verdoro_chats_list_screen.dart';
import 'screens/all_plants_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/discover_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  _preloadFallbackFonts();
  await dotenv.load(fileName: ".env");

  // Set a stable transparent status bar baseline.
  // The exact icon brightness is updated later based on theme.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
    ),
  );

  try {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  } on FirebaseException catch (e) {
    if (e.code != 'duplicate-app') rethrow;
  }
  FirebaseFirestore.instance.settings = const Settings(
    persistenceEnabled: true, 
    cacheSizeBytes: Settings.CACHE_SIZE_UNLIMITED,
  );
  debugPrint('Firebase ready');
  // Health score refresh is deferred to after sign-in (see _DigitalConservatoryAppState)

  // Init local notifications safely; skip if vacation mode is active
  try {
    await NotificationService().initialize();
    final prefs = await SharedPreferences.getInstance();
    final vacationOn = prefs.getBool('vacation_mode_enabled') ?? false;
    if (!vacationOn) {
      await NotificationService().scheduleDailyVerdoroInsight();
    }
  } catch (e) {
    debugPrint('Warning: Notification initialization failed: $e');
  }

  // BUG 1 FIX: Read the saved theme BEFORE runApp so the very first frame
  // already has the correct ThemeMode � this prevents the system dark-mode
  // from flickering in while _loadTheme() is awaited inside initState.
  final savedThemeMode = await ThemeService().getThemeMode();

  runApp(
    ProviderScope(
      child: DigitalConservatoryApp(initialThemeMode: savedThemeMode),
    ),
  );
}

class DigitalConservatoryApp extends StatefulWidget {
  final ThemeMode initialThemeMode;
  const DigitalConservatoryApp({super.key, this.initialThemeMode = ThemeMode.light});

  @override
  State<DigitalConservatoryApp> createState() => _DigitalConservatoryAppState();
}

class _DigitalConservatoryAppState extends State<DigitalConservatoryApp> {
  // Initialised from widget.initialThemeMode (which was read before runApp),
  // so the saved preference is honoured from the very first frame.
  late ThemeMode _themeMode;
  Locale _locale = const Locale('en');
  late final Stream<User?> _authStream;

  @override
  void initState() {
    super.initState();
    _themeMode = widget.initialThemeMode;
    // _authStream is initialized once here and never recreated � this is
    // intentional to prevent StreamBuilder from resubscribing on every rebuild
    // which was the root cause of the "sign-in spins forever" bug.
    _authStream = FirebaseAuth.instance.authStateChanges();
    LocaleService.getInitialLocale().then((loc) {
      if (mounted) setState(() => _locale = loc);
    });
  }

  void _onThemeChanged(bool isDark) {
    setState(() {
      _themeMode = isDark ? ThemeMode.dark : ThemeMode.light;
    });
    _applySystemUiOverlay(isDark);
  }

  void _onLocaleChanged(Locale locale) {
    setState(() {
      _locale = locale;
    });
    LocaleService.saveLocale(locale.languageCode);
  }

  /// Keeps status bar icon brightness in sync with the app theme so that
  /// Flutter's PlatformPlugin does not fight against our initial setting.
  void _applySystemUiOverlay(bool isDark) {
    SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(
        statusBarColor: Colors.transparent,
        statusBarIconBrightness:
            isDark ? Brightness.light : Brightness.dark,
        statusBarBrightness:
            isDark ? Brightness.dark : Brightness.light,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Verdoro',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      themeMode: _themeMode,
      locale: _locale,
      localizationsDelegates: AppLocalizations.localizationsDelegates,
      supportedLocales: AppLocalizations.supportedLocales,
      home: StreamBuilder<User?>(
        stream: _authStream,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              body: Center(child: CircularProgressIndicator()),
            );
          }
          if (snapshot.hasData && snapshot.data != null) {
            return MainTabScreen(onThemeChanged: _onThemeChanged, onLocaleChanged: _onLocaleChanged);
          }
          return SignupScreen(onThemeChanged: _onThemeChanged, onLocaleChanged: _onLocaleChanged);
        },
      ),
    );
  }
}

class MainTabScreen extends StatefulWidget {
  final ValueChanged<bool> onThemeChanged;
  final ValueChanged<Locale> onLocaleChanged;
  const MainTabScreen({super.key, required this.onThemeChanged, required this.onLocaleChanged});

  @override
  State<MainTabScreen> createState() => _MainTabScreenState();
}

class _MainTabScreenState extends State<MainTabScreen> {
  int _currentIndex = 0;

  Widget _getScreen(int index) {
    switch (index) {
      case 0:
        return HomeScreen(
          onThemeChanged: widget.onThemeChanged,
          onLocaleChanged: widget.onLocaleChanged,
        );
      case 1:
        return const AllPlantsScreen();
      case 2:
        return const VerdoroChatsListScreen();
      case 3:
        return const DiscoverScreen();
      default:
        return const SizedBox.shrink();
    }
  }

  Widget _buildNavItem(int index, IconData icon, String label, bool isDark) {
    final isActive = _currentIndex == index;
    final activeBg = AppColors.forest100;
    final inactiveBg = Colors.transparent;

    final activeIconColor = AppColors.forest700;
    final inactiveIconColor = isDark ? AppColors.darkTextSecondary : AppColors.bone400;

    return GestureDetector(
      onTap: () {
        setState(() {
          _currentIndex = index;
        });
      },
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 200),
        padding: EdgeInsets.symmetric(
          horizontal: isActive ? 14 : 12,
          vertical: 6,
        ),
        decoration: BoxDecoration(
          color: isActive ? activeBg : inactiveBg,
          borderRadius: BorderRadius.circular(20),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(
              icon,
              size: 22,
              color: isActive ? activeIconColor : inactiveIconColor,
            ),
            if (isActive) ...[
              const SizedBox(height: 2),
              Text(
                label,
                style: const TextStyle(
                  fontSize: 10,
                  fontWeight: FontWeight.w600,
                  color: AppColors.forest700,
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Scaffold(
      body: Stack(
        children: [
          Padding(
            padding: const EdgeInsets.only(bottom: 80),
            child: _getScreen(_currentIndex),
          ),
          Positioned(
            bottom: 16,
            left: 20,
            right: 20,
            child: Container(
              decoration: BoxDecoration(
                color: isDark ? AppColors.darkSurface : Colors.white,
                borderRadius: BorderRadius.circular(28),
                boxShadow: const [
                  BoxShadow(
                    color: Color(0x24224A1E),
                    blurRadius: 24,
                    offset: Offset(0, 6),
                  ),
                ],
              ),
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 10),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceAround,
                children: [
                  _buildNavItem(0, CupertinoIcons.house, 'Home', isDark),
                  _buildNavItem(1, CupertinoIcons.leaf_arrow_circlepath, 'Garden', isDark),
                  _buildNavItem(2, CupertinoIcons.chat_bubble_text, 'Verdoro', isDark),
                  _buildNavItem(3, CupertinoIcons.compass, 'Discover', isDark),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}




Future<void> scheduleHealthScoreRefresh() async {
  try {
    final uid = FirebaseAuth.instance.currentUser?.uid;
    if (uid != null) {
      final plantsQuery = await FirebaseFirestore.instance.collection('users').doc(uid).collection('plants').get();
      for (var doc in plantsQuery.docs) {
        final data = doc.data();
        if (data.containsKey('healthScore')) {
          await doc.reference.update({
            'previousHealthScore': data['healthScore'],
          });
        }
      }
      await FirestoreService().computeAllHealthScores(uid);
    }
  } catch (e) {
    debugPrint('Health score refresh error: $e');
  }
}

void _preloadFallbackFonts() {
  GoogleFonts.notoSansArabic();
  GoogleFonts.notoSansJp();
  GoogleFonts.notoSansKr();
  GoogleFonts.notoSansSc();
  GoogleFonts.notoColorEmoji();
}
