$arbDir = "c:\Projects\Flora_v0.1\Flora\lib\l10n"
$arbFiles = Get-ChildItem -Path $arbDir -Filter "app_*.arb"

$replacements = @(
    @{ From = '"Ask Flora"'; To = '"Ask Verdoro"' },
    @{ From = '"Ask Flora anything"'; To = '"Ask Verdoro anything"' },
    @{ From = '"Ask Flora anything..."'; To = '"Ask Verdoro anything..."' },
    @{ From = '"Ask Flora..."'; To = '"Ask Verdoro..."' },
    @{ From = '"Flora is thinking"'; To = '"Verdoro is thinking"' },
    @{ From = '"Continue with Flora"'; To = '"Continue with Verdoro"' },
    @{ From = '"Analyze with Flora"'; To = '"Analyze with Verdoro"' },
    @{ From = '"Chat with Flora"'; To = '"Chat with Verdoro"' },
    @{ From = '"Ask Flora about this topic'; To = '"Ask Verdoro about this topic' },
    @{ From = '"Ask Flora about this"'; To = '"Ask Verdoro about this"' },
    @{ From = '"Ask Flora for advice'; To = '"Ask Verdoro for advice' },
    @{ From = '"Ask Flora About This Plant"'; To = '"Ask Verdoro About This Plant"' },
    @{ From = '"Not sure what to write? Ask Flora'; To = '"Not sure what to write? Ask Verdoro' },
    @{ From = '"Flora noticed something'; To = '"Verdoro noticed something' },
    @{ From = '"Flora reminds you exactly when to care"'; To = '"Verdoro reminds you exactly when to care"' },
    @{ From = '"Point your camera and Flora names it"'; To = '"Point your camera and Verdoro names it"' },
    @{ From = '"Generated by Flora every Sunday"'; To = '"Generated by Verdoro every Sunday"' },
    @{ From = '"Opening Flora'; To = '"Opening Verdoro' },
    @{ From = '"Please sign in to continue with Flora."'; To = '"Please sign in to continue with Verdoro."' },
    @{ From = '"Could not open Flora: "'; To = '"Could not open Verdoro: "' },
    @{ From = '"Add a plant to get a care schedule built automatically by Flora"'; To = '"Add a plant to get a care schedule built automatically by Verdoro"' },
    @{ From = '"Flora builds a smart care calendar'; To = '"Verdoro builds a smart care calendar' },
    @{ From = 'a personalized care plan from Flora."'; To = 'a personalized care plan from Verdoro."' },
    @{ From = 'Meet Flora'; To = 'Meet Verdoro' },
    @{ From = '"Flora has personalized your care schedule based on your home conditions"'; To = '"Verdoro has personalized your care schedule based on your home conditions"' },
    @{ From = '"Flora is analyzing your plants'; To = '"Verdoro is analyzing your plants' },
    @{ From = '"Please log in to use Flora."'; To = '"Please log in to use Verdoro."' },
    @{ From = '"Start your first conversation with Flora"'; To = '"Start your first conversation with Verdoro"' },
    @{ From = '"Flora is reviewing your plants'; To = '"Verdoro is reviewing your plants' },
    @{ From = '"Flora Chat Messages"'; To = '"Verdoro Chat Messages"' },
    @{ From = '"Welcome to Flora"'; To = '"Welcome to Verdoro"' },
    @{ From = '"Join Flora and start your plant journey."'; To = '"Join Verdoro and start your plant journey."' },
    @{ From = '"Welcome to Flora!'; To = '"Welcome to Verdoro!' },
    @{ From = '"Flora knows your entire plant collection'; To = '"Verdoro knows your entire plant collection' },
    @{ From = '"Analyze with Flora to get health score"'; To = '"Analyze with Verdoro to get health score"' },
    @{ From = '"FLORA AI EXPERT ANSWER"'; To = '"VERDORO AI EXPERT ANSWER"' },
    @{ From = "Flora's analysis."; To = "Verdoro's analysis." },
    @{ From = '"Add your first plant and Flora will build'; To = '"Add your first plant and Verdoro will build' },
    @{ From = '"Digital Conservatory"'; To = '"Verdoro"' },
    @{ From = '"Welcome to Digital Conservatory"'; To = '"Welcome to Verdoro"' },
    @{ From = '"Grown with Digital Conservatory"'; To = '"Grown with Verdoro"' },
    @{ From = '"Check out my plant on Digital Conservatory!"'; To = '"Check out my plant on Verdoro!"' },
    @{ From = '"Check out this plant discussion on Digital Conservatory: "'; To = '"Check out this plant discussion on Verdoro: "' },
    @{ From = '"Digital Conservatory v1.0.0"'; To = '"Verdoro v1.0.0"' },
    @{ From = '"DIGITAL CONSERVATORY PLANT PASSPORT"'; To = '"VERDORO PLANT PASSPORT"' },
    @{ From = '"Hi, I'; To = '"Hi, I' },
    @{ From = "Hi! I'm Flora"; To = "Hi! I'm Verdoro" },
    @{ From = "I'm Flora "; To = "I'm Verdoro " }
)

foreach ($file in $arbFiles) {
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $orig = $content
    foreach ($r in $replacements) {
        $content = $content.Replace($r.From, $r.To)
    }
    if ($content -ne $orig) {
        [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.Encoding]::UTF8)
        Write-Host "Updated: $($file.Name)"
    } else {
        Write-Host "No changes: $($file.Name)"
    }
}
Write-Host "ARB update complete"
